/*
Given a long vector of strings, print the strings that contain the strings generated by numeric string str.

string searchIn [] = {
            "prateek", "sneha", "deepak", "arnav", "shikha", "palak",
            "utkarsh", "divyam", "vidhi", "sparsh", "akku"
    };
For example, if the input is 26 and the string is coding, then output should be coding since 26 can produce co which is contained in coding.

Input Format
A numeric string str

Constraints
len(str) < 10
No of strings in the vector < 10

Output Format
Each matched string from the given vector.

Sample Input
34
Sample Output
vidhi
divyam
sneha
Explanation
34 will result into combinations :

*dg         *eg         *fg
*dh            *eh         *fh
*di            *ei         *fi
Corresponding strings are output.

vidhi contains dh
divyam contains di
sneha contains eh
*/
#include<bits/stdc++.h>
using namespace std;
vector<string> keypad = { " ", ".+@$", "abc", "def", "ghi", "jkl" , "mno", "pqrs" , "tuv", "wxyz" }, searchIn = { "prateek", "sneha", "deepak", "arnav", "shikha", "palak", "utkarsh", "divyam", "vidhi", "sparsh", "akku"};

void search(string key) {
	for (int i = 0; i < searchIn.size(); i++) {
		if (searchIn[i].find(key) != string::npos) {
			cout << searchIn[i] << endl;
		}
	}
}

void printCodes(string digits, int index = 0, string out = "") {
	if (index >= digits.length()) {
		search(out);
		return;
	}
	int digit = digits[index] - '0';
	for (int i = 0; i < keypad[digit].length(); i++) {
		printCodes(digits, index + 1, out + keypad[digit][i]);
	}
}

int main() {
	string digits;
	cin >> digits;
	printCodes(digits);
	return 0;
}